### ISSUE TITLE
Hi Andreas Gerlach !

### ISSUE THREAD

**Issue by jonatasfreitasv** [appelgriebsch/electron-boilerplate#1]
I like your project and i started some tests.

But i missed some things like Grunt and unit and functional tests.

If i implement the items that i missed, i come back with a pull request, right?

You would like to write a README for more information?

**Comment by appelgriebsch** [comment]
Yes, we can do it like this. Feel free to submit pull requests and I will take a look in documenting what is available right now. Thx for your kindly feedback.

**Comment by jonatasfreitasv** [comment]
Look this project, is the best: https://github.com/szwacz/electron-boilerplate

**Comment by appelgriebsch** [comment]
Yeah, I know this one and tried it first, but find it quite heavy-weight as it copies everything around at every build. Also it was not using the latest toolkit for packaging apps (electron-builder, electron-packager) afaik...

**Comment by jonatasfreitasv** [comment]
True, it is very heavy, I did a pull request on this project and some questions too, but the project owner did not seem friendly = /.

**Comment by appelgriebsch** [comment]
Added initial grunt-build support to create release versions of the application. Next step: create os-specific installers (dmg, win32, deb, rpm).

**Comment by jonatasfreitasv** [comment]
Nice @appelgriebsch !!!

I started electron documentation translation to en -us , i'm absorbing a lot of knowledge , next moments i will Contribute to your boilerplate ;).

https://github.com/atom/electron/tree/master/docs-translations/pt-BR

**Comment by appelgriebsch** [comment]
Initial version of image creation added!

**Comment by appelgriebsch** [comment]
Working build solution on OSX (x64), Win32 (ia32) and Linux (x64) via Grunt.
